# Generated by Django 4.2.16 on 2025-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='impact',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Impact (1=Low, 5=High)'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='likelihood',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Likelihood (1=Low, 5=High)'),
        ),
    ]
