# Generated by Django 4.2.16 on 2025-09-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='regulation_update',
            field=models.ForeignKey(db_column='regulation_update_id', on_delete=django.db.models.deletion.CASCADE, to='checklist.regulationupdate'),
        ),
    ]
