# Generated by Django 4.2.16 on 2025-08-28 02:37

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_checklistitem_impact_checklistitem_likelihood'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='admin_notes',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Admin/internal comments', null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='mitigation_steps',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Describe mitigation steps for this risk.', null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='impact',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True, default=1, help_text='Impact (1=Low, 5=High)'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='likelihood',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True, default=1, help_text='Likelihood (1=Low, 5=High)'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['user', 'completed'], name='checklist_c_user_id_e21934_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['regulation_update', 'completed'], name='checklist_c_regulat_048d80_idx'),
        ),
    ]
